"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

[aws]
disabled = true

[azure]
disabled = true

[battery]
disabled = true

[gcloud]
disabled = true

[line_break]
disabled = true

[username]
show_always = true
format = "[$user@]($style)"

[hostname]
ssh_only = false
format = "[$hostname]($style):"

[directory]
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

